micronaut:
  application:
    name: my-pseudo-service
  server:
    port: 10210
    cors:
      enabled: true
    thread-selection: AUTO
    max-request-size: 2gb
    multipart:
      max-file-size: 2gb

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api-docs/swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /api-docs/rapidoc/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /api-docs/redoc/**

  security:
    enabled: true
    intercept-url-map:
      - pattern: /api-docs/**
        httpMethod: GET
        access:
          - isAnonymous()